project:
  type: website
  output-dir: docs

website:
  favicon: "img/rmgis.png"
  title: "C5025HF Research methods and Geographical Information Systems"
  sidebar:
    logo: "img/rmgis.png"
    style: "docked"
    search: true
    contents: 
      - section: "Sessions"
        contents:
          - syntax-basics.qmd
          - data-structures.qmd
          - indexing.qmd
          - tidy-data.qmd
          - eda.qmd
          - galton.qmd
          - chisquare.qmd
          - gosset.qmd
          - t-test.qmd
          - fisher.qmd
          - 1-way-anova.qmd
format:
  html:
    highlight-style: a11y
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

