---
title: "Mini-project"
format: html
editor: visual
---

## Synopsis

We have developed a new high-potential enhancer of biological nitrogen fixation (BNF) with nanotechnology which we believe can revolutionalise agriculture. It works by fostering long term relationships between beneficial soil microbes and plants. The technology works by affecting the gene expression of certain nitrogen-fixing bacteria such that they react to the presence of certain root exudates from a plant, and the presence of other bacteria that have been exposed to the same species in the past. This "wakes-up" dormant nitrogen fixing bacteria in a soil at an early crop growth stage, contributing to higher net BNF in the soil and better outcomes for the crop. Essentially, the nanotechnology builds a microbe-based memory system that allows for plants to be regrown in the same soil and with an enhanced chance of early BNF. We tested our nanotechnology against a no-treatment control and a regular BNF inoculant in randomized and replicated experiments with soya bean in 2016 and 2017. The experiments were randomized once, so the treatments occurred in the same exact plot in both years. The nanotechnology was only applied in 2016, so that we can examine if the effect lasts into 2017. Our hypothesis is that our treatment will outperform the regular BNF inoculant and the untreated control in yield in both years. We also hypothesise that the yield of the nanotechnology treatment on the same plot will improve in the second year. Finally, we believe that the regular BNF inoculation is still better than the control because these soils have poor nitrogen fixing bacteria due to excessive monocropping with cereals overtime.

Using the attached tidy data, please formulate appropriate null hypotheses to test our three alternate hypotheses. Conduct a statistical analysis based on the ANOVA technique and report whether our hypotheses are true or not. Conduct all the analysis in R and document the code comprehensively in a Quarto document.

[Data](https://github.com/C7091/_C7091-Professional-Skills-for-Data-Science/blob/main/2024_25/Content/Assessments/Mini-project/data.xlsx)
